ci: add ci and issue templates
kRHYME7/Hyde-cli pull request #56
Opened 2024-05-15 14:11 UTC by rubiin

Github CI for automating releases based on google release please, maintains semver so you don't have to worry

Do make a repository secret along with your github token  called `GITHUB_TOKEN` with these permissions 
https://github.com/googleapis/release-please-action#workflow-permissions

demo: https://github.com/rubiin/ultimate-nest/pull/443

2024-05-15 14:17 UTC, rubiin commented
Also if you want to start from a particular version lets say mark the first version of Hyde-cli as `0.2.0`,
simply add a file called  `.release-please-manifest.json`
```json
{
    ".": "0.2.0"
}

```

2024-05-16 12:49 UTC, kRHYME7 commented
@rubiin Thanks, we can do that now, but I am waiting to lock the CLI to a tagged version of HyDE. Can we wait a little longer?  I hope before that we add the TUI installer. 

This way the CLI can follow the structure of the Tagged release of HyDE.

2024-05-16 12:51 UTC, rubiin commented
This is nothing of a breaking change. Think of like it a project management with release as extras

2024-05-16 12:56 UTC, kRHYME7 commented
Great!  I got some feature req from you before merging.

2024-05-16 12:58 UTC, rubiin commented
Just be sure to create a person access token with name `TOKEN_GITHUB`
the token can be created https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/managing-your-personal-access-tokens

I think you just neeed repo read write permissions.
If you feel lazy click all boxes

2024-05-17 00:29 UTC, kRHYME7 requested changes

2024-05-17 04:58 UTC, rubiin commented on .github/ISSUE_TEMPLATE/bug_report.yml
we have to make it work . I will push a next PR afterwards

2024-05-17 04:59 UTC, rubiin commented on .release-please-manifest.json
this is just for initialization so that the action bot knows what release to make next. we can change that with a blank commit as well

2024-05-17 05:16 UTC, rubiin commented
I have modified the release as 0.6.0 , though we could also do this with empty commit. This can be now merged.
Also make sure to write commits as fix: , feat: , etc in conevntional commit as those changes are only picked

2024-05-17 06:42 UTC, merged

2024-05-17 07:47 UTC, rubiin commented
@kRHYME7 could you create a tag 0.5.0 and manually release one 
![image](https://github.com/kRHYME7/Hyde-cli/assets/8222059/49b03cba-2e60-4794-bf35-baba2ddd7cc5)

2024-05-17 07:57 UTC, kRHYME7 commented
Did you mean 0.6.0 ? 

Thanks for baring with me 😁

2024-05-17 08:41 UTC, rubiin commented
can be anything like 0.5.5.
No worries , it was hit and trial for me too

2024-05-17 08:51 UTC, kRHYME7 commented
Done  I pushed it as v0.5.1

2024-05-17 08:57 UTC, rubiin commented
![image](https://github.com/kRHYME7/Hyde-cli/assets/8222059/6df625d4-0189-4c3e-b2ad-3e5571c166ec)

Not showing in here . I guess you created tags only . If you got to the url ,https://github.com/kRHYME7/Hyde-cli/releases , it will let you create a release. On the tag select 0.5.1

2024-05-17 09:39 UTC, kRHYME7 commented
created a pre-release is that okay ?

2024-05-17 09:41 UTC, rubiin commented
lets test . Can you maybe do some small doc changes

2024-05-17 09:58 UTC, kRHYME7 commented
at any file? like README?

2024-05-17 10:00 UTC, rubiin commented
yup

2024-05-17 10:15 UTC, kRHYME7 commented
This turns green now!  Should I celebrate 🤣? 

![image](https://github.com/kRHYME7/Hyde-cli/assets/53417443/efcda40a-7a56-48ad-9fdc-68272e5f1723)



Also, I built my AUR on top of the CLI so that I can just clone it across devices. (that's what I planned)

![image](https://github.com/kRHYME7/Hyde-cli/assets/53417443/6e8d7b6f-aa26-4363-bad5-de4bfbf17cb4)

Can I just ignore this error for now?

2024-05-17 10:56 UTC, rubiin commented
Looks good. Now do a litlle commit with feat: some message . Can be blank commit as well

`git commit --allow-empty -m "feat: Trigger Build"`

2024-05-17 10:59 UTC, rubiin commented
https://github.com/rubiin/Hyde-cli/pull/1

Just testing here as well looks fine now :D

2024-05-17 11:37 UTC, kRHYME7 commented
ops 
![image](https://github.com/kRHYME7/Hyde-cli/assets/53417443/f61b7b51-e6a9-42e1-906c-5d2768f5cadc)

2024-05-17 11:45 UTC, rubiin commented
I think it does not take pre-release do a release

2024-05-17 11:46 UTC, rubiin commented
https://github.com/rubiin/Hyde-cli/releases/tag/0.5.2 check here this is a valid release. Dont do pre release .

2024-05-17 11:47 UTC, rubiin commented
That happens when it does not find any releases so it will go through all the commits thus hitting rate limit

2024-05-17 11:53 UTC, kRHYME7 commented
Always got this messages 
```
      message: 'Resource not accessible by integration',

✖ Error when creating branch
✖ RequestError [HttpError]: Error creating Pull Request: Resource not accessible by integration
    at /home/runner/work/_actions/googleapis/release-please-action/v4/dist/index.js:11190:21
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
✔ Retry attempt #5...
    at async createBranch (/home/runner/work/_actions/googleapis/release-please-action/v4/dist/index.js:18125:26)
    at async branch (/home/runner/work/_actions/googleapis/release-please-action/v4/dist/index.js:18153:9)
    at async retry.retries (/home/runner/work/_actions/googleapis/release-please-action/v4/dist/index.js:18913:48)
    at async createPullRequest (/home/runner/work/_actions/googleapis/release-please-action/v4/dist/index.js:18913:24)
    at async /home/runner/work/_actions/googleapis/release-please-action/v4/dist/index.js:56858:30
    at async GitHub.createPullRequest (/home/runner/work/_actions/googleapis/release-please-action/v4/dist/index.js:57956:20)
    at async Manifest.createOrUpdatePullRequest (/home/runner/work/_actions/googleapis/release-please-action/v4/dist/index.js:58574:32)
    at async Promise.all (i
    
    
    ```


Is this  not related to the TOKEN ?

2024-05-17 11:59 UTC, kRHYME7 commented
Here

![image](https://github.com/kRHYME7/Hyde-cli/assets/53417443/c880aeeb-6711-4f8d-bc70-382937bf284a)

2024-05-17 12:05 UTC, kRHYME7 commented
Update the release is successful now